version: '3.4'
services:
  openvino-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: openvino-dev
    image: openvino-dev
    stdin_open: true
    tty: true
    command: bash

  openvino-runtime:
    build:
      context: .
      dockerfile: Dockerfile
      target: openvino-runtime
    image: openvino-runtime
    stdin_open: true
    tty: true
    command: bash

  sampleapp-dev:
    build:
      context: ./sample-app
      dockerfile: Dockerfile
      target: sampleapp-dev
    image: sampleapp-dev
    stdin_open: true
    tty: true
    command: bash

  sampleapp-runtime:
    build:
      context: ./sample-app
      dockerfile: Dockerfile
      target: sampleapp-runtime
    image: sampleapp-runtime
    stdin_open: true
    tty: true
    container_name: sampleapp-runtime
    command: "watch -n 5 /home/openvino/run.sh"
    security_opt:
      - no-new-privileges
      - label=level:s0:c1,c2
    read_only: true
    restart: "on-failure:5"
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
